export const COLORS = {
  BG_GREY: "#E0F7FA",
  TABLE_HEADER: "#00796B",
  TABLE_HEADER_TEXT: "#FFFFFF",
  TABLE_ROW_ODD: "#B2DFDB",
  TABLE_ROW_EVEN: "#E0F2F1",
  TABLE_ROW_HOVER: "#80CBC4",
  PAGINATION_ACTIVE: "#0288D1",
  PAGINATION_INACTIVE: "#B3E5FC",
  PAGINATION_HOVER: "#0277BD",
  PAGINATION_DISABLED: "#B0BEC5",
};
